### ISSUE TITLE
メッセージ数が少ないと下詰めで表示される

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#433]
少し気になる

**Comment by sapphi-red** [comment]
```scss
.MessagesScroller_viewport_26hZp {
    display: flex;
    flex-flow: column;
    /* justify-content: flex-end; */
    min-height: 100%;
}
```
これするだけで変わりそうですが、これスクロール周りに影響しそうですか？
